CREATE TABLE weather_data (
    id SERIAL PRIMARY KEY,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temperature DECIMAL(5, 2),
    feels_like DECIMAL(5, 2),
    wind_speed DECIMAL(5, 2),
    gust_speed DECIMAL(5, 2),
    wind_degree INT,
    wind_direction VARCHAR(255),
    pressure DECIMAL(5, 2),
    humidity INT,
    cloud INT,
    weather_condition VARCHAR(255),
    city_name VARCHAR(255) NOT NULL,
    region VARCHAR(255),
    country VARCHAR(255),
    latitude DECIMAL(10, 6),
    longitude DECIMAL(10, 6),
    time_zone_id VARCHAR(50),
    local_time TIMESTAMP,
    sunrise TIME,
    sunset TIME,
    moonrise TIME,
    moonset TIME,
    moon_phase VARCHAR(255),
    moon_illumination INT,
    forecast_date DATE,
    time_zone VARCHAR(50),
    -- ip_address VARCHAR(15),
    -- history_date DATE,
    -- search_query VARCHAR(255),
    -- future_date DATE
);
